name: CMIPortalParticleHotfix
version: '${version}'
main: art.ryanstew.cmiportalparticlehotfix.CMIPortalParticleHotfix
api-version: '1.20'
author: RuntimeRyn
depend: [CMI, CMILib]

commands:
    cmiportalparticlehotfix:
        description: Fix all CMI portals
        permission: cmiportalparticlehotfix.fixportals
        aliases: [particlehotfix, fixportals, portalfix]

permissions:
    cmiportalparticlehotfix.fixportals:
        description: Permission to use /portalfix.
        default: op